development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: flowspace-bakery_development

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: flowspace-bakery_production
